name: Build
on:
  push:
  pull_request:

jobs:
  determine-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo ${{ env.BRANCH_NAME }} > branch-name.txt
      - uses: actions/upload-artifact@v3
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          name: branch-name
          path: branch-name.txt
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci
        
      - name: Get branch name
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/download-artifact@v3
        with:
          name: branch-name
      
      - run: |
          if [ -f branch-name/branch-name.txt ]; then
            echo "BRANCH_NAME=$(cat branch-name/branch-name.txt)" >> $GITHUB_ENV
          fi

      - name: Build
        run: npm run build
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          BRANCH_NAME: ${{ jobs.determine-name.outputs.BRANCH_NAME }}

      - name: Build
        run: npm run build
        if: ${{ github.ref == 'refs/heads/main' }}
