name: Deploy Production
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://flyboat.biishop.org
    concurrency:
      group: deploy-prod
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - name: Build zip
        run: |
          cd dist
          zip -r ../main.zip *
      - name: Deploy to Production
        id: deploy
        run: |
          curl -X 'POST' --fail-with-body \
          'https://flyboat-dev.biishop.org/' \
          -H 'accept: application/json' \
          -H 'Content-Type: multipart/form-data' \
          -F 'key=${{ secrets.DEPLOY_KEY }}' \
          -F 'data=@main.zip'
