name: Deploy Staging
on:
  push:
    branches-ignore:
      - main
  pull_request_target:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.NEW_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - run: echo ${{ github.event_name }} ${{ github.ref }} ${{ github.sha }}
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request_target'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request_target'
        shell: bash
        run: echo "BRANCH_NAME=pr-$(jq --raw-output .pull_request_target.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - name: Build zip
        run: |
          cd dist
          zip -r ../${{ env.BRANCH_NAME }}.flyboat-dev.zip *
      - name: Deploy to Staging
        id: deploy
        run: |
          curl -X 'POST' --fail-with-body \
          'https://flyboat-dev.biishop.org/' \
          -H 'accept: application/json' \
          -H 'Content-Type: multipart/form-data' \
          -F 'key=${{ secrets.DEPLOY_KEY }}' \
          -F 'data=@${{ env.BRANCH_NAME }}.flyboat-dev.zip'
          echo "NEW_URL=http://${{ env.BRANCH_NAME }}.flyboat-dev.biishop.org" >> $GITHUB_OUTPUT
      - name: Leave comment
        if: github.event_name == 'pull_request_target'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Deployed to staging: ${{ steps.deploy.outputs.NEW_URL }}
