name: Deploy Staging
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml@main
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Deploy to Staging
        run: ls -l distT
